name: whatfreewords
description: A library for converting coordinates to words and back using a Feistel network.
version: 1.0.0
homepage: https://github.com/randogoth/whatfreewords

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.21.0